export default {
  // 1. common — general UI labels, buttons, actions
  common: {
    appText: "النص التطبيقي",
    screen: "الشاشة",
    header: "الرأس",
    back: "خلف",
    action: "فعل",
    primaryButton: "زر رئيسي",
    secondaryButton: "زر ثانوي",
    iconButton: "أيقونة",
    card: "بطاقة",
    emptyState: "حالة فارغة",
    icon: "أيقونة",
    title: "عنوان",
    subtitle: "عنوان فرعي",
    loading: "جارٍ التحميل",
    error: "خطأ",
    retry: "إعادة المحاولة",
    notFound: "الصفحة غير موجودة",
    notFoundBackToHome: "العودة للصفحة الرئيسية",
    confirmDialog: "تأكيد",
    confirmTitle: "تأكيد",
    confirmMessage: "هل أنت متأكد من رغبتك في المتابعة؟",
    confirmCancel: "إلغاء",
    confirmOk: "موافق",
    money: "د.ج",
    positive: "إيجابي",
    negative: "سلبي",
    search: "بحث",
    placeholder: "بحث...",
    formField: "حقل",
    label: "اسم الحقل",
    errorMessage: "رسالة خطأ",
    statusPaid: " مدفوع",
    statusPartial: "جزئي",
    statusCancelled: "ملغي",
  },

  // 2. onboarding — onboarding flow strings
  onboarding: {
    appText: "نص التطبيق",
    screen: "شاشة",
    header: "رأس",
    back: "خلف",
    title: "مرحباً بك في دكان OS",
    subtitle: "تطبيق يساعد التجار الصغار",
    description: "سجل المبيعات، تتبع الزبائن، إدارة المخزون",
    getStarted: "ابدأ",
    skip: "تخطي",
  },

  // 3. navigation — tab labels, headers
  navigation: {
    home: "الرئيسية",
    products: "المنتجات",
    sales: "المبيعات",
    customers: "الزبائن",
    catalogue: "الكاتالوج",
    more: "أكثر",
    dashboard: "لوحة التحكم",
    settings: "الإعدادات",
    profile: "الملف التعريفي",
    logout: "تسجيل الخروج",
  },

  // 4. dashboard — dashboard cards, summaries
  dashboard: {
    title: "لوحة التحكم",
    totalSales: "إجمالي المبيعات",
    totalCustomers: "إجمالي الزبائن",
    lowStockAlert: "تنبيه نقص المخزون",
    estimatedProfit: "الأرباح التقديرية",
    todaySales: "مبيعات اليوم",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    stockValue: "قيمة المخزون",
    noSalesYet: "لا مبيعات بعد",
    newSale: "مبيعة جديدة",
  },

  // 5. products — product management
  products: {
    title: "المنتجات",
    subtitle: "ادارة المنتجات",
    addProduct: "إضافة منتج",
    editProduct: "تعديل المنتج",
    name: "اسم المنتج",
    description: "الوصف",
    price: "السعر",
    costPrice: "سعر التكلفة",
    barcode: "الباركود",
    sku: "SKU",
    category: "الفئة",
    status: "الحالة",
    active: "نشط",
    inactive: "غير نشط",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    noProductsYet: "لا توجد منتجات بعد",
  },

  // 6. inventory — stock, movements
  inventory: {
    title: "المخزون",
    subtitle: "إدارة المخزون",
    totalItems: "إجمالي العناصر",
    lowStock: "مخزون منخفض",
    outOfStock: "نفذ المخزون",
    restock: "تزويد",
    addStock: "إضافة مخزون",
    removeStock: "إزالة مخزون",
    movementTitle: "حركة مخزون",
    movementIn: "دخول",
    movementOut: "خروج",
    date: "التاريخ",
    quantity: "الكمية",
    product: "منتج",
    noStockYet: "لا توجد حركة مخزون بعد",
  },

  // 7. sales — sale flow, cart, checkout
  sales: {
    title: "المبيعات",
    subtitle: "إدارة المبيعات",
    newSale: "مبيعة جديدة",
    cart: "العربة",
    checkout: "الصندوق",
    paymentMethod: "طريقة الدفع",
    cash: "كاش",
    electronic: "إلكتروني",
    mixed: "مختلط",
    partial: "محدد",
    credit: "ائتمان",
    amount: "المبلغ",
    quantity: "الكمية",
    total: "الإجمالي",
    change: "الباقي",
    pay: "ادفع",
    confirmSale: "تأكيد البيع",
    saleCancelled: "تم إلغاء البيع",
    saleCompleted: "تم إتمام البيع",
    noSalesYet: "لا توجد مبيعات بعد",
  },

  // 8. customers — customer management
  customers: {
    title: "الزبائن",
    subtitle: "إدارة الزبائن",
    addCustomer: "إضافة زبون",
    editCustomer: "تعديل زبون",
    name: "اسم الزبون",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    debt: "الدَّيْن",
    creditLimit: "حد الائتمان",
    totalDebt: "إجمالي الدين",
    payments: "المدفوعات",
    addPayment: "إضافة دفعة",
    viewDetails: "عرض التفاصيل",
    noCustomersYet: "لا توجد زبائن بعد",
  },

  // 9. payments — payment recording
  payments: {
    title: "المدفوعات",
    subtitle: "تسجيل المدفوعات",
    receivePayment: "استلام دفعة",
    paymentAmount: "مبلغ الدفعة",
    paymentMethod: "طريقة الدفع",
    cashPayment: "دفعة كاش",
    electronicPayment: "دفعة إلكترونية",
    reference: "مرجع",
    date: "التاريخ",
    amountReceived: "المبلغ المستلم",
    remainingBalance: "الرصيد المتبقي",
    paymentCompleted: "تم إتمام الدفعة",
    noPaymentsYet: "لا توجد مدفوعات بعد",
  },

  // 10. catalogue — catalogue generation
  catalogue: {
    title: "الكاتالوج",
    subtitle: "إنتاج الكاتالوج",
    generateCatalogue: "إنشاء الكاتالوج",
    productsIncluded: "منتجات مشمولة",
    excludeCustomerData: "استبعاد بيانات الزبائن",
    generate: "إنشاء",
    csvFormat: "تنسيق CSV",
    exporting: "جاري الإخراج",
    catalogueExported: "تم تصدير الكاتالوج",
    noProductsForCatalogue: "لا منتجات للكاتالوج",
  },

  // 11. receipts — receipt text
  receipts: {
    title: "الفاتورة",
    subtitle: "نص الفاتورة",
    storeName: "اسم المتجر",
    storeAddress: "عنوان المتجر",
    date: "التاريخ",
    time: "الوقت",
    saleItems: "عناصر البيع",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    totalAmount: "المبلغ الإجمالي",
    amountPaid: "المبلغ المدفوع",
    changeDue: "الباقي",
    customerName: "اسم الزبون",
    phoneNumber: "رقم الهاتف",
    thankYou: "شكراً لزيارتكم",
    comeAgain: "نتمنى لكم يوماً سعيداً",
  },

  // 12. exports — CSV export labels
  exports: {
    title: "التصدير",
    subtitle: "تصدير البيانات",
    exportCSV: "تصدير CSV",
    exportSelected: "تصدير المحدد",
    exportAll: "تصدير الكل",
    columns: "الأعمدة",
    dateRange: "نطاق التاريخ",
    from: "من",
    to: "إلى",
    exportingData: "جاري تصدير البيانات",
    exportCompleted: "تم التصدير",
    exportFailed: "فشل التصدير",
    selectingData: "حدد البيانات التي تريد تصديرها",
    noDataToExport: "لا بيانات للتصدير",
  },

  // 13. settings — settings sections
  settings: {
    title: "الإعدادات",
    subtitle: "إعدادات التطبيق",
    general: "عام",
    language: "اللغة",
    currency: "العملة",
    notifications: "الإشعارات",
    about: "حول",
    version: "الإصدار",
    rateApp: "قيِّم التطبيق",
    shareApp: "شارك التطبيق",
    logoutAllSessions: "تسجيل الخروج من جميع الجلسات",
    resetApp: "إعادة تعيين التطبيق",
    languageArabic: "العربية",
    languageFrench: "Français",
    languageEnglish: "English",
    default: "افتراضي",
  },

  // 14. voice — voice command messages
  voice: {
    title: "الأوامر الصوتية",
    subtitle: "تعرف علىCommands",
    listening: "جارٍ الاستماع",
    listeningError: "خطأ في الاستماع",
    commandNotRecognized: "لا يمكن التعرف على الأمر",
    sayProductName: "اسم المنتج",
    sayPrice: "السعر",
    sayQuantity: "الكمية",
    startSale: "بيع بدء",
    cancelSale: "بيع إلغاء",
    takePhoto: "التقاط صورة",
  },

  // 15. errors — error messages
  errors: {
    title: "خطأ",
    genericError: "حدث خطأ عام",
    networkError: "خطأ في الشبكة",
    tryAgain: "حاول مرة أخرى",
    somethingWentWrong: "حدث خطأ ما",
    invalidInput: " مدخل غير صالح",
    requiredField: "حقل مطلوب",
    unableToLoad: "لا يمكن تحميل البيانات",
    unableToSave: "لا يمكن حفظ البيانات",
    operationCancelled: "تم إلغاء العملية",
  },

  // 16. confirmations — confirmation dialog messages
  confirmations: {
    title: "تأكيد",
    message: "هل أنت متأكد؟",
    cancel: "إلغاء",
    ok: "موافق",
    deleteItem: "حذف هذا العنصر؟",
    deleteSale: "حذف هذه المباعة؟",
    clearDatabase: "مسح قاعدة البيانات؟",
    thisActionCannotBeUndone: "لا يمكن التراجع عن هذا الإجراء",
    yesDelete: "نعم، احذف",
    noKeep: "لا، احتفظ",
  },

  // 17. emptyStates — empty list messages
  emptyStates: {
    title: "لا توجد عناصر",
    subtitle: "الم lista فارغة",
    description: "لا توجد عناصر بعد. أضف أول عنصر لك",
    addFirstItem: "أضف أول عنصر",
    noProducts: "لا منتجات",
    noCustomers: "لا عملاء",
    noSales: "لا مبيعات",
    noPayments: "لا مدفوعات",
    noInventory: "لا حركة مخزون",
  },

  // 18. permissions — permission request messages
  permissions: {
    title: "طلبات الأذونات",
    camera: "وصول للكاميرا",
    microphone: "وصول للميكروفون",
    storage: "وصول للتخزين",
    location: "وصول للموقع",
    cameraDescription: "هذه الميزة تتطلب وصول للكاميرا",
    microphoneDescription: "هذه الميزة تتطلب وصول للميكروفون",
    storageDescription: "هذه الميزة تتطلب وصول للتخزين",
    locationDescription: "هذه الميزة تتطلب وصول للموقع",
    deny: "رفض",
    allow: "سماح",
  },
};
