export default {
  // 1. common — general UI labels, buttons, actions
  common: {
    appText: "النص التطبيقي",
    screen: "الشاشة",
    header: "الرأس",
    back: "خلف",
    action: "فعل",
    primaryButton: "زر رئيسي",
    secondaryButton: "زر ثانوي",
    iconButton: "أيقونة",
    card: "بطاقة",
    emptyState: "حالة فارغة",
    icon: "أيقونة",
    title: "عنوان",
    subtitle: "عنوان فرعي",
    loading: "جارٍ التحميل",
    error: "خطأ",
    retry: "إعادة المحاولة",
    notFound: "الصفحة غير موجودة",
    notFoundBackToHome: "العودة للصفحة الرئيسية",
    confirmDialog: "تأكيد",
    confirmTitle: "تأكيد",
    confirmMessage: "هل أنت متأكد من رغبتك في المتابعة؟",
    confirmCancel: "إلغاء",
    confirmOk: "موافق",
    money: "د.ج",
    positive: "إيجابي",
    negative: "سلبي",
    search: "بحث",
    placeholder: "بحث...",
    formField: "حقل",
    label: "اسم الحقل",
    errorMessage: "رسالة خطأ",
    statusPaid: " مدفوع",
    statusPartial: "جزئي",
    statusCancelled: "ملغي",
  },

  // 2. onboarding — onboarding flow strings
  onboarding: {
    appText: "نص التطبيق",
    screen: "شاشة",
    header: "رأس",
    back: "خلف",
    title: "مرحباً بك في دكان OS",
    subtitle: "تطبيق يساعد التجار الصغار",
    description: "سجل المبيعات، تتبع الزبائن، إدارة المخزون",
    getStarted: "ابدأ",
    skip: "تخطي",
  },

  // 3. navigation — tab labels, headers
  navigation: {
    home: "الرئيسية",
    products: "المنتجات",
    sales: "المبيعات",
    customers: "الزبائن",
    catalogue: "الكاتالوج",
    more: "أكثر",
    dashboard: "لوحة التحكم",
    settings: "الإعدادات",
    profile: "الملف التعريفي",
    logout: "تسجيل الخروج",
  },

  // 4. dashboard — dashboard cards, summaries
  dashboard: {
    title: "لوحة التحكم",
    totalSales: "إجمالي المبيعات",
    totalCustomers: "إجمالي الزبائن",
    lowStockAlert: "تنبيه نقص المخزون",
    estimatedProfit: "الأرباح التقديرية",
    todaySales: "مبيعات اليوم",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    stockValue: "قيمة المخزون",
    noSalesYet: "لا مبيعات بعد",
    newSale: "مبيعة جديدة",
  },

  // 5. products — product management
  products: {
    title: "المنتجات",
    subtitle: "تتبع المخزون والسلع",
    addProduct: "إضافة منتج",
    editProduct: "تعديل المنتج",
    newItem: "عنصر جديد",
    name: "اسم المنتج",
    description: "الوصف",
    price: "السعر",
    costPrice: "سعر التكلفة",
    barcode: "الباركود",
    sku: "SKU",
    category: "الفئة",
    status: "الحالة",
    active: "نشط",
    inactive: "غير نشط",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    noProductsYet: "لا توجد منتجات بعد",
    totalItems: "إجمالي العناصر",
    totalValue: "إجمالي القيمة",
    lowStockCount: "مخزون منخفض ({{count}})",
    searchPlaceholder: "بحث بالاسم أو رمز SKU",
    filterAll: "الكل",
    filterLowStock: "مخزون منخفض",
    filterOutOfStock: "نفذ",
    filterArchived: "مؤرشف",
    itemsCount: "{{count}} عناصر",
    lowStockBadge: "{{count}} مخزون منخفض",
    inStock: "متوفر",
    outOfStock: "نفذ المخزون",
    lowStock: "مخزون منخفض",
    lowStockMin: "مخزون منخفض (أدنى: {{min}})",
    stock: "المخزون",
    onHand: "المتوفر حالياً",
    minThreshold: "الحد الأدنى",
    stockStatus: "حالة المخزون",
    needsRestock: "بحاجة لتزويد",
    normalStock: "طبيعي",
    salePrice: "سعر البيع",
    estimatedProfit: "الربح التقديري",
    profitMargin: "هامش الربح",
    sellingPrice: "سعر البيع",
    costAndProfit: "التكلفة والربح",
    adjustStock: "تعديل المخزون",
    inventoryHistory: "سجل حركات المخزون",
    recentMovements: "أحدث حركات المخزون",
    noHistory: "لا يوجد سجل حركات بعد",
    lowStockAlert: "تنبيه مخزون منخفض",
    lowStockAlertDesc: "بقي {{stock}} فقط. الحد الأدنى للتنبيه هو {{min}}.",
    generalInformation: "معلومات عامة",
    itemDetails: "تفاصيل العنصر",
    pricingAndMargins: "الأسعار وهوامش الربح",
    stockInventory: "إدارة المخزون",
    openingStock: "المخزون الأولي",
    unit: "الوحدة",
    units: "وحدات",
    minAlertThreshold: "الحد الأدنى للتنبيه",
    safeFloor: "حد الأمان",
    alertsWhenLow: "تنبيه عند انخفاض المخزون لهذا الحد",
    skuBarcodeOptional: "رمز SKU / الباركود (اختياري)",
    categoryOptional: "الفئة (اختياري)",
    newCategory: "فئة جديدة",
    addCategoryPrompt: "أدخل اسم الفئة الجديدة",
    scanBarcode: "مسح الباركود",
    valid: "صالح",
    productNameRequired: "اسم المنتج مطلوب",
    saveProduct: "حفظ المنتج",
    productUpdated: "تم تحديث المنتج بنجاح",
    productCreated: "تم إنشاء المنتج بنجاح",
    adjustmentMethod: "طريقة التعديل",
    setNewTotal: "تحديد إجمالي جديد",
    addRemove: "إضافة / خصم (+/−)",
    newTotalQuantity: "إجمالي الكمية الجديدة",
    adjustmentQuantity: "كمية التعديل (+/−)",
    currentOnHand: "المتوفر في المتجر",
    adjustmentReason: "سبب التعديل",
    reasonRequired: "مطلوب",
    reasonDelivery: "شحنة بضاعة جديدة / تزويد",
    reasonCorrection: "تصحيح جرد المخزون",
    reasonDamaged: "سلع تالفة أو منتهية الصلاحية",
    reasonReturn: "إرجاع من زبون",
    reasonOther: "أخرى",
    referenceNote: "المرجع / ملاحظة",
    referenceNoteOptional: "اختياري",
    referenceNotePlaceholder: "مثال: وصل استلام #BL-4890، اسم المورد",
    impactSummary: "ملخص أثر التعديل",
    newInventoryBalance: "رصيد المخزون الجديد:",
    inventoryValueChange: "تغير قيمة المخزون:",
    atCost: "بسعر التكلفة",
    confirmAdjustment: "تأكيد التعديل",
    adjustmentSuccess: "تم تعديل المخزون بنجاح",
    archiveProduct: "أرشفة المنتج",
    reactivateProduct: "إعادة تفعيل المنتج",
    archiveConfirm: "هل أنت متأكد من أرشفة هذا المنتج؟",
    copiedToClipboard: "تم النسخ إلى الحافظة",
    inventoryRulesTitle: "قواعد المخزون والتحكم بالمنتج",
    inventoryRulesSubtitle: "تحديد عتبات التنبيه وقواعد البيع الخاصة بهذا المنتج",
    sellingPolicyLabel: "سياسة البيع عند نفاد المخزون",
    strictPolicy: "صارم: منع البيع عند نفاد المخزون (0)",
    allowNegativePolicy: "السماح بالمخزون السالب (مواصلة البيع)",
    presetThresholds: "خيارات سريعة",
    targetRestockQty: "كمية التزويد الموصى بها",
    targetRestockQtyOptional: "حجم الطلبية المفضل عند الشراء من المورد",
    stockStatusHealthy: "مخزون كافٍ",
    stockStatusLow: "تنبيه انخفاض المخزون",
    stockStatusOut: "نفد المخزون",
  },

  // 6. inventory — stock, movements
  inventory: {
    title: "المخزون",
    subtitle: "إدارة المخزون",
    totalItems: "إجمالي العناصر",
    lowStock: "مخزون منخفض",
    outOfStock: "نفذ المخزون",
    restock: "تزويد",
    addStock: "إضافة مخزون",
    removeStock: "إزالة مخزون",
    movementTitle: "حركة مخزون",
    movementIn: "دخول",
    movementOut: "خروج",
    date: "التاريخ",
    quantity: "الكمية",
    product: "منتج",
    noStockYet: "لا توجد حركة مخزون بعد",
  },

  sell: {
    title: "الصندوق والمبيعات",
    subtitle: "إصدار فواتير سريع • الكاتالوج والباركود",
    scanBarcode: "مسح الرمز الشريطي",
    allProducts: "جميع المنتجات",
    frequentItems: "المنتجات الأكثر طلباً",
    add: "إضافة",
  },

  // 7. sales — sale flow, cart, checkout
  sales: {
    title: "المبيعات",
    subtitle: "إدارة المبيعات",
    newSale: "مبيعة جديدة",
    cart: "العربة",
    checkout: "الصندوق",
    paymentMethod: "طريقة الدفع",
    cash: "كاش",
    electronic: "إلكتروني",
    mixed: "مختلط",
    partial: "محدد",
    credit: "ائتمان",
    amount: "المبلغ",
    quantity: "الكمية",
    total: "الإجمالي",
    change: "الباقي",
    pay: "ادفع",
    confirmSale: "تأكيد البيع",
    saleCancelled: "تم إلغاء البيع",
    saleCompleted: "تم إتمام البيع",
    noSalesYet: "لا توجد مبيعات بعد",
  },

  // 8. customers — customer management
  customers: {
    title: "الزبائن",
    subtitle: "إدارة الزبائن",
    activeDebt: "ديون نشطة",
    activityTimeline: "سجل النشاط",
    add: "إضافة",
    addCustomer: "إضافة زبون",
    addPayment: "إضافة دفعة",
    all: "الكل",
    amountPlaceholder: "0",
    archived: "المؤرشفون",
    carnetDette: "دفتر الديون • سجل المحل",
    cash: "نقداً (كاش)",
    cashDescription: "دفع نقدي مباشر في المحل",
    cleared: "تمت التسوية",
    clientSince: "زبون منذ",
    closeWithoutSending: "إغلاق بدون إرسال",
    confirmPayment: "تأكيد الدفع",
    creditLimit: "حد الائتمان",
    creditLimitHelp: "أقصى دين مسموح به قبل التنبيه",
    creditSaleHistory: "سجل المبيعات بالدين",
    creditSales: "مبيعات بالدين",
    currentDebt: "الدين الحالي",
    customAmount: "مبلغ مخصص",
    debt: "الدَّيْن",
    debtToCollect: "ديون للتحصيل",
    edahabia: "إلكتروني",
    edahabiaDescription: "بطاقة الذهبية / CIB",
    editCustomer: "تعديل زبون",
    electronic: "إلكتروني",
    email: "البريد الإلكتروني",
    fullDebt: "كامل الدين",
    hasDebt: "عليه دين",
    identityAndContact: "الهوية ومعلومات الاتصال",
    immediateDue: "مستحق فوراً",
    impactOnBalance: "الأثر على الرصيد",
    invalidAmount: "مبلغ الدفعة غير صالح",
    merchantNote: "ملاحظة التاجر",
    messagePreview: "معاينة فورية",
    name: "اسم الزبون",
    nameHelp: "الاسم الكامل أو اللقب المعروف",
    nameRequired: "اسم الزبون مطلوب",
    newBalance: "رصيد الدين الجديد",
    newCustomer: "زبون جديد",
    noCustomersYet: "لا توجد زبائن بعد",
    noDebt: "مسدد",
    noHistory: "لا توجد سجلات بعد",
    noNotes: "لم تتم إضافة ملاحظات",
    notFound: "الزبون غير موجود",
    noTimeline: "لا يوجد نشاط بعد",
    note: "ملاحظة الزبون",
    noteHelp: "سياق مفيد يظهر أثناء الدفع وفي ملخصات الديون",
    notePlaceholder: "مثال: جار الطابق الثاني، زبون صباحي دائم",
    notes: "ملاحظات",
    overdue: "متأخر",
    overPaymentWarning: "المبلغ يتجاوز الدين الحالي",
    overPaymentWarningDetails: "الدين المتبقي: {{remaining}} دج. الفائض: {{excess}} دج.",
    overPaymentWarningTitle: "تنبيه حد الدفع",
    paymentAmount: "مبلغ الدفعة",
    paymentCleared: "تم استلام {{amount}} دج من {{customer}}",
    paymentFailed: "فشل تسجيل الدفعة",
    paymentHistory: "سجل المدفوعات",
    paymentMethod: "طريقة الدفع",
    paymentReminderPreview: "معاينة تذكير الدفع",
    payments: "المدفوعات",
    paymentSuccess: "تم تسجيل الدفعة",
    paymentToApply: "الدفعة المطبقة",
    phone: "الهاتف",
    phoneHelp: "يستخدم لتذكيرات الدفع عبر واتساب والإيصالات",
    phonePlaceholder: "0550 12 34 56",
    recordPayment: "تسجيل دفعة",
    referenceNote: "مرجع / ملاحظة",
    reminderSent: "تمت مشاركة التذكير بنجاح",
    saveCustomer: "حفظ الزبون",
    searchPlaceholder: "بحث بالاسم أو الهاتف",
    selectChannel: "قناة الإرسال الرئيسية",
    selectLanguage: "لغة الرسالة",
    sendReminder: "إرسال التذكير",
    sendViaSMS: "إرسال عبر الرسائل القصيرة",
    sendViaWhatsApp: "إرسال عبر واتساب",
    settled: "مسدد",
    settlementDetails: "تفاصيل التسوية",
    shareReminder: "مشاركة تذكير (واتساب)",
    sms: "رسالة SMS مباشرة",
    totalCustomers: "إجمالي الزبائن",
    totalDebt: "إجمالي الدين",
    viewDetails: "عرض التفاصيل",
    whatsapp: "واتساب",
    withDebt: "عليهم دين",
  },

  // 9. payments — payment recording
  payments: {
    title: "المدفوعات",
    subtitle: "تسجيل المدفوعات",
    receivePayment: "استلام دفعة",
    paymentAmount: "مبلغ الدفعة",
    paymentMethod: "طريقة الدفع",
    cashPayment: "دفعة كاش",
    electronicPayment: "دفعة إلكترونية",
    reference: "مرجع",
    date: "التاريخ",
    amountReceived: "المبلغ المستلم",
    remainingBalance: "الرصيد المتبقي",
    paymentCompleted: "تم إتمام الدفعة",
    noPaymentsYet: "لا توجد مدفوعات بعد",
  },

  // 10. catalogue — catalogue generation
  catalogue: {
    title: "الكاتالوج",
    subtitle: "إنتاج الكاتالوج",
    generateCatalogue: "إنشاء الكاتالوج",
    productsIncluded: "منتجات مشمولة",
    excludeCustomerData: "استبعاد بيانات الزبائن",
    generate: "إنشاء",
    csvFormat: "تنسيق CSV",
    exporting: "جاري الإخراج",
    catalogueExported: "تم تصدير الكاتالوج",
    noProductsForCatalogue: "لا منتجات للكاتالوج",
    settingsTitle: "إعدادات الكاتالوج",
    settingsSubtitle: "كتيب الزبائن القابل للمشاركة",
    readyToShare: "جاهز للمشاركة",
    instantShowcase: "واجهة عرض فورية",
    instantShowcaseDesc: "أنشئ كتيب منتجات أنيق بنقرة واحدة. هوامش أرباحك وحساباتك تظل سرية تماماً.",
    displayPreferences: "تفضيلات العرض",
    showRetailPrices: "عرض أسعار البيع",
    showRetailPricesDesc: "يعرض سعر البيع بجانب كل منتج",
    hideOutOfStock: "إخفاء المنتجات غير المتوفرة",
    hideOutOfStockDesc: "يخفي تلقائياً المنتجات ذات الكمية الصفرية",
    publicHeader: "الترويسة العامة ومعلومات الاتصال",
    shopHeaderTitle: "اسم المتجر في الترويسة",
    orderWhatsApp: "واتساب / هاتف الطلبات",
    storeLocation: "عنوان المتجر",
    welcomeNote: "رسالة ترحيب الكتيب",
    guaranteedPrivacy: "سرية مضمونة",
    guaranteedPrivacyDesc: "أسعار الشراء الداخلية وحسابات الديون وأرقام المخزون الداخلي مستبعدة تماماً من الكتيب العام.",
    selectProductsBtn: "اختيار المنتجات",
    selectProductsTitle: "اختيار المنتجات",
    selectProductsSubtitle: "اختر المنتجات المراد تضمينها في الكتيب",
    productsSelected: "منتجات محددة",
    selectAll: "تحديد الكل",
    deselect: "إلغاء التحديد",
    searchPlaceholder: "البحث عن منتجات للتضمين...",
    previewCatalogueBtn: "معاينة الكاتالوج",
    backToSettings: "الرجوع للإعدادات",
    previewTitle: "معاينة الكاتالوج",
    previewSubtitle: "معاينة كتيب الزبائن العام",
    publicDocument: "وثيقة زبائن عامة",
    publicDocNotice: "الأرقام المالية الداخلية محجوبة تماماً",
    shareAsPdf: "مشاركة بصيغة PDF",
    shareAsWhatsApp: "مشاركة كنص / رسالة واتساب",
    editSelection: "تعديل الاختيار",
    available: "متوفر",
    outOfStock: "غير متوفر",
    onOrder: "تحت الطلب",
    thanksMessage: "شكراً لثقتكم بنا !",
    validNotice: "صالح حسب المخزون المتوفر",
    itemsCount: "منتجات",
    noProductsFound: "لا توجد منتجات مطابقة",
    noProductsFoundDesc: "جرب البحث عن منتجات أخرى أو امسح التصفية",
  },

  // 11. receipts — receipt text
  receipts: {
    title: "الفاتورة",
    subtitle: "نص الفاتورة",
    storeName: "اسم المتجر",
    storeAddress: "عنوان المتجر",
    date: "التاريخ",
    time: "الوقت",
    saleItems: "عناصر البيع",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    totalAmount: "المبلغ الإجمالي",
    amountPaid: "المبلغ المدفوع",
    changeDue: "الباقي",
    customerName: "اسم الزبون",
    phoneNumber: "رقم الهاتف",
    thankYou: "شكراً لزيارتكم",
    comeAgain: "نتمنى لكم يوماً سعيداً",
  },

  // 12. exports — CSV export labels
  exports: {
    title: "التصدير",
    subtitle: "تصدير البيانات",
    exportCSV: "تصدير CSV",
    exportSelected: "تصدير المحدد",
    exportAll: "تصدير الكل",
    columns: "الأعمدة",
    dateRange: "نطاق التاريخ",
    from: "من",
    to: "إلى",
    exportingData: "جاري تصدير البيانات",
    exportCompleted: "تم التصدير",
    exportFailed: "فشل التصدير",
    selectingData: "حدد البيانات التي تريد تصديرها",
    noDataToExport: "لا بيانات للتصدير",
  },

  // 13. settings — settings sections
  settings: {
    title: "الإعدادات",
    subtitle: "إعدادات التطبيق",
    general: "عام",
    language: "اللغة",
    currency: "العملة",
    notifications: "الإشعارات",
    about: "حول",
    version: "الإصدار",
    rateApp: "قيِّم التطبيق",
    shareApp: "شارك التطبيق",
    logoutAllSessions: "تسجيل الخروج من جميع الجلسات",
    resetApp: "إعادة تعيين التطبيق",
    languageArabic: "العربية",
    languageFrench: "Français",
    languageEnglish: "English",
    default: "افتراضي",
    theme: "المظهر",
    themeSubtitle: "الوضع الفاتح، الداكن، أو حسب إعدادات الجهاز",
    themeSystem: "تلقائي",
    themeLight: "فاتح",
    themeDark: "داكن",
    themeSystemDesc: "مطابقة المظهر مع إعدادات نظام الهاتف",
    themeLightDesc: "مظهر نهاري ناصع ومريح",
    themeDarkDesc: "مظهر ليلي داكن ومريح للعين",
    themeUpdated: "تم تحديث مظهر التطبيق بنجاح",
  },

  // 14. voice — voice command messages
  voice: {
    title: "الأوامر الصوتية",
    subtitle: "تعرف علىCommands",
    listening: "جارٍ الاستماع",
    listeningError: "خطأ في الاستماع",
    commandNotRecognized: "لا يمكن التعرف على الأمر",
    sayProductName: "اسم المنتج",
    sayPrice: "السعر",
    sayQuantity: "الكمية",
    startSale: "بيع بدء",
    cancelSale: "بيع إلغاء",
    takePhoto: "التقاط صورة",
  },

  // 15. errors — error messages
  errors: {
    title: "خطأ",
    genericError: "حدث خطأ عام",
    networkError: "خطأ في الشبكة",
    tryAgain: "حاول مرة أخرى",
    somethingWentWrong: "حدث خطأ ما",
    invalidInput: " مدخل غير صالح",
    requiredField: "حقل مطلوب",
    unableToLoad: "لا يمكن تحميل البيانات",
    unableToSave: "لا يمكن حفظ البيانات",
    operationCancelled: "تم إلغاء العملية",
  },

  // 16. confirmations — confirmation dialog messages
  confirmations: {
    title: "تأكيد",
    message: "هل أنت متأكد؟",
    cancel: "إلغاء",
    ok: "موافق",
    deleteItem: "حذف هذا العنصر؟",
    deleteSale: "حذف هذه المباعة؟",
    clearDatabase: "مسح قاعدة البيانات؟",
    thisActionCannotBeUndone: "لا يمكن التراجع عن هذا الإجراء",
    yesDelete: "نعم، احذف",
    noKeep: "لا، احتفظ",
  },

  // 17. emptyStates — empty list messages
  emptyStates: {
    title: "لا توجد عناصر",
    subtitle: "الم lista فارغة",
    description: "لا توجد عناصر بعد. أضف أول عنصر لك",
    addFirstItem: "أضف أول عنصر",
    noProducts: "لا منتجات",
    noCustomers: "لا عملاء",
    noSales: "لا مبيعات",
    noPayments: "لا مدفوعات",
    noInventory: "لا حركة مخزون",
  },

  // 18. permissions — permission request messages
  permissions: {
    title: "طلبات الأذونات",
    camera: "وصول للكاميرا",
    microphone: "وصول للميكروفون",
    storage: "وصول للتخزين",
    location: "وصول للموقع",
    cameraDescription: "هذه الميزة تتطلب وصول للكاميرا",
    microphoneDescription: "هذه الميزة تتطلب وصول للميكروفون",
    storageDescription: "هذه الميزة تتطلب وصول للتخزين",
    locationDescription: "هذه الميزة تتطلب وصول للموقع",
    deny: "رفض",
    allow: "سماح",
  },
};
