export default {
  // 1. common — general UI labels, buttons, actions
  common: {
    appText: "App Text",
    screen: "Screen",
    header: "Header",
    back: "Back",
    action: "Action",
    primaryButton: "Primary",
    secondaryButton: "Secondary",
    iconButton: "Icon",
    card: "Card",
    emptyState: "Empty State",
    icon: "Icon",
    title: "Title",
    subtitle: "Subtitle",
    loading: "Loading",
    error: "Error",
    retry: "Retry",
    notFound: "Page not found",
    notFoundBackToHome: "Back to Home",
    confirmDialog: "Confirm",
    confirmTitle: "Confirmation",
    confirmMessage: "Are you sure you want to proceed?",
    confirmCancel: "Cancel",
    confirmOk: "OK",
    money: "DZD",
    positive: "Positive",
    negative: "Negative",
    search: "Search",
    placeholder: "Search...",
    formField: "Field",
    label: "Label",
    errorMessage: "Error",
    statusPaid: "Paid",
    statusPartial: "Partial",
    statusCancelled: "Cancelled"
  },

  // 2. onboarding — onboarding flow strings
  onboarding: {
    appText: "App Text",
    screen: "Screen",
    header: "Header",
    back: "Back",
    title: "Welcome to Dukkan OS",
    subtitle: "App for Algerian micro-entrepreneurs",
    description: "Record sales, track customers, manage inventory",
    getStarted: "Get Started",
    skip: "Skip"
  },

  // 3. navigation — tab labels, headers
  navigation: {
    home: "Home",
    products: "Products",
    sales: "Sales",
    customers: "Customers",
    catalogue: "Catalogue",
    more: "More",
    dashboard: "Dashboard",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout"
  },

  // 4. dashboard — dashboard cards, summaries
  dashboard: {
    title: "Dashboard",
    totalSales: "Total Sales",
    totalCustomers: "Total Customers",
    lowStockAlert: "Low Stock Alert",
    estimatedProfit: "Estimated Profit",
    todaySales: "Today's Sales",
    thisWeek: "This Week",
    thisMonth: "This Month",
    stockValue: "Stock Value",
    noSalesYet: "No sales yet",
    newSale: "New Sale"
  },

  // 5. products — product management
  products: {
    title: "Products",
    subtitle: "Inventory & stock tracker",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    newItem: "New Item",
    name: "Name",
    description: "Description",
    price: "Price",
    costPrice: "Cost Price",
    barcode: "Barcode",
    sku: "SKU",
    category: "Category",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    noProductsYet: "No products yet",
    totalItems: "Total Items",
    totalValue: "Total Value",
    lowStockCount: "Low Stock ({{count}})",
    searchPlaceholder: "Search by name or SKU",
    filterAll: "All",
    filterLowStock: "Low Stock",
    filterOutOfStock: "Out of Stock",
    filterArchived: "Archived",
    itemsCount: "{{count}} items",
    lowStockBadge: "{{count}} Low Stock",
    inStock: "In stock",
    outOfStock: "Out of stock",
    lowStock: "Low stock",
    lowStockMin: "Low stock (min: {{min}})",
    stock: "Stock",
    onHand: "On Hand",
    minThreshold: "Min. Threshold",
    stockStatus: "Stock Status",
    needsRestock: "Needs Restock",
    normalStock: "Normal",
    salePrice: "Sale Price",
    estimatedProfit: "Estimated Profit",
    profitMargin: "Profit Margin",
    sellingPrice: "Selling Price",
    costAndProfit: "Cost & Profit",
    adjustStock: "Adjust Stock",
    inventoryHistory: "Inventory History",
    recentMovements: "Recent stock movements",
    noHistory: "No inventory history yet",
    lowStockAlert: "Low Stock Alert",
    lowStockAlertDesc: "Only {{stock}} left. Minimum threshold is set to {{min}}.",
    generalInformation: "General Information",
    itemDetails: "Item Details",
    pricingAndMargins: "Pricing & Margins",
    stockInventory: "Stock Inventory",
    openingStock: "Opening Stock",
    unit: "Unit",
    units: "units",
    minAlertThreshold: "Minimum Alert Threshold",
    safeFloor: "Safe floor",
    alertsWhenLow: "Alerts you when stock dips to this level",
    skuBarcodeOptional: "SKU / Barcode (Optional)",
    categoryOptional: "Category (Optional)",
    newCategory: "New Category",
    addCategoryPrompt: "Enter new category name",
    scanBarcode: "Scan Barcode",
    valid: "Valid",
    productNameRequired: "Product name is required",
    saveProduct: "Save Product",
    productUpdated: "Product updated successfully",
    productCreated: "Product created successfully",
    adjustmentMethod: "Adjustment Method",
    setNewTotal: "Set New Total",
    addRemove: "Add / Remove (+/−)",
    newTotalQuantity: "New Total Quantity",
    adjustmentQuantity: "Adjustment Quantity (+/−)",
    currentOnHand: "Current On-Hand",
    adjustmentReason: "Reason for Adjustment",
    reasonRequired: "Required",
    reasonDelivery: "New stock delivery / Restock",
    reasonCorrection: "Inventory count correction",
    reasonDamaged: "Damaged or expired goods",
    reasonReturn: "Customer return",
    reasonOther: "Other",
    referenceNote: "Reference / Note",
    referenceNoteOptional: "Optional",
    referenceNotePlaceholder: "e.g., Delivery slip #BL-4890, wholesaler name",
    impactSummary: "Adjustment Impact Summary",
    newInventoryBalance: "New inventory balance:",
    inventoryValueChange: "Inventory value change:",
    atCost: "at cost",
    confirmAdjustment: "Confirm Adjustment",
    adjustmentSuccess: "Stock adjusted successfully",
    archiveProduct: "Archive Product",
    reactivateProduct: "Reactivate Product",
    archiveConfirm: "Are you sure you want to archive this product?",
    copiedToClipboard: "Copied to clipboard",
  },

  // 6. inventory — stock, movements
  inventory: {
    title: "Inventory",
    subtitle: "Inventory Management",
    totalItems: "Total Items",
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    restock: "Restock",
    addStock: "Add Stock",
    removeStock: "Remove Stock",
    movementTitle: "Stock Movement",
    movementIn: "In",
    movementOut: "Out",
    date: "Date",
    quantity: "Quantity",
    product: "Product",
    noStockYet: "No stock movements yet"
  },

  // 7. sales — sale flow, cart, checkout
  sales: {
    title: "Sales",
    subtitle: "Sales Flow",
    newSale: "New Sale",
    cart: "Cart",
    checkout: "Checkout",
    paymentMethod: "Payment Method",
    cash: "Cash",
    electronic: "Electronic",
    mixed: "Mixed",
    partial: "Partial",
    credit: "Credit",
    amount: "Amount",
    quantity: "Quantity",
    total: "Total",
    change: "Change",
    pay: "Pay",
    confirmSale: "Confirm Sale",
    saleCancelled: "Sale Cancelled",
    saleCompleted: "Sale Completed",
    noSalesYet: "No sales yet"
  },

  // 8. customers — customer management
  customers: {
    title: "Customers",
    subtitle: "Customer Management",
    activeDebt: "Active Debt",
    activityTimeline: "Activity Timeline",
    add: "Add",
    addCustomer: "Add Customer",
    addPayment: "Add Payment",
    all: "All",
    amountPlaceholder: "0",
    archived: "Archived",
    carnetDette: "Carnet Dette • Retail Store Ledger",
    cash: "Cash",
    cashDescription: "Direct cash over the counter",
    cleared: "Cleared",
    clientSince: "Client Since",
    closeWithoutSending: "Close without sending",
    confirmPayment: "Confirm Payment",
    creditLimit: "Credit Limit",
    creditLimitHelp: "Maximum debt allowed before alert",
    creditSaleHistory: "Credit Sale History",
    creditSales: "Credit Sales",
    currentDebt: "Current Debt",
    customAmount: "Custom",
    debt: "Debt",
    debtToCollect: "Debt to Collect",
    edahabia: "Electronic",
    edahabiaDescription: "Edahabia / CIB POS",
    editCustomer: "Edit Customer",
    electronic: "Electronic",
    email: "Email",
    fullDebt: "Full Debt",
    hasDebt: "Debt",
    identityAndContact: "Identity & Contact",
    immediateDue: "Immediate Due",
    impactOnBalance: "Impact On Balance",
    invalidAmount: "Invalid payment amount",
    merchantNote: "Merchant Note",
    messagePreview: "Instant Preview",
    name: "Name",
    nameHelp: "Full name or familiar shop nickname",
    nameRequired: "Customer name is required",
    newBalance: "New Debt Balance",
    newCustomer: "New Customer",
    noCustomersYet: "No customers yet",
    noDebt: "Settled",
    noHistory: "No records yet",
    noNotes: "No notes added",
    notFound: "Customer not found",
    noTimeline: "No activity yet",
    note: "Customer Note",
    noteHelp: "Helpful context visible on checkout and carnet summaries",
    notePlaceholder: "e.g., Neighbor from 2nd floor, regular customer",
    notes: "Notes",
    overdue: "Overdue",
    overPaymentWarning: "Payment amount exceeds current debt",
    overPaymentWarningDetails: "Remaining debt: {{remaining}} DZD. Excess: {{excess}} DZD.",
    overPaymentWarningTitle: "Payment Limit Notice",
    paymentAmount: "Payment Amount",
    paymentCleared: "{{amount}} DZD received from {{customer}}",
    paymentFailed: "Failed to record payment",
    paymentHistory: "Payment History",
    paymentMethod: "Payment Method",
    paymentReminderPreview: "Payment Reminder Preview",
    payments: "Payments",
    paymentSuccess: "Payment Recorded",
    paymentToApply: "Payment to apply",
    phone: "Phone",
    phoneHelp: "Used for WhatsApp payment reminders & receipts",
    phonePlaceholder: "0550 12 34 56",
    recordPayment: "Record Payment",
    referenceNote: "Reference / Note",
    reminderSent: "Reminder shared successfully",
    saveCustomer: "Save Customer",
    searchPlaceholder: "Search by name or phone",
    selectChannel: "Primary Dispatch Channel",
    selectLanguage: "Message Language",
    sendReminder: "Send Reminder",
    sendViaSMS: "Send via SMS",
    sendViaWhatsApp: "Send via WhatsApp",
    settled: "Settled",
    settlementDetails: "Settlement Details",
    shareReminder: "Share Reminder (WhatsApp)",
    sms: "SMS Direct",
    totalCustomers: "Total Customers",
    totalDebt: "Total Debt",
    viewDetails: "View Details",
    whatsapp: "WhatsApp",
    withDebt: "With Debt",
  },

  // 9. payments — payment recording
  payments: {
    title: "Payments",
    subtitle: "Payment Recording",
    receivePayment: "Receive Payment",
    paymentAmount: "Payment Amount",
    paymentMethod: "Payment Method",
    cashPayment: "Cash Payment",
    electronicPayment: "Electronic Payment",
    reference: "Reference",
    date: "Date",
    amountReceived: "Amount Received",
    remainingBalance: "Remaining Balance",
    paymentCompleted: "Payment Completed",
    noPaymentsYet: "No payments yet"
  },

  // 10. catalogue — catalogue generation
  catalogue: {
    title: "Catalogue",
    subtitle: "Catalogue Generation",
    generateCatalogue: "Generate Catalogue",
    productsIncluded: "Products Included",
    excludeCustomerData: "Exclude Customer Data",
    generate: "Generate",
    csvFormat: "CSV Format",
    exporting: "Exporting",
    catalogueExported: "Catalogue Exported",
    noProductsForCatalogue: "No products for catalogue",
    settingsTitle: "Catalogue Settings",
    settingsSubtitle: "Shareable Customer Brochure",
    readyToShare: "Ready to Share",
    instantShowcase: "Instant Showcase",
    instantShowcaseDesc: "Create a clean, elegant product brochure for your shoppers in one tap. Your backend margins and tabs stay completely private.",
    displayPreferences: "Display Preferences",
    showRetailPrices: "Show retail prices",
    showRetailPricesDesc: "Displays customer selling price beside each item",
    hideOutOfStock: "Hide out-of-stock items",
    hideOutOfStockDesc: "Automatically filters out zero-quantity goods from public view",
    publicHeader: "Customer Header & Contact",
    shopHeaderTitle: "Shop Header Title",
    orderWhatsApp: "Order WhatsApp / Mobile",
    storeLocation: "Store Location / Address",
    welcomeNote: "Brochure Welcome Note",
    guaranteedPrivacy: "Confidentiality Guaranteed",
    guaranteedPrivacyDesc: "Internal purchase figures, store tabs, supplier SKUs, and warehouse counts are strictly excluded from all public brochures.",
    selectProductsBtn: "Select Products",
    selectProductsTitle: "Select Products",
    selectProductsSubtitle: "Choose products to include in the brochure",
    productsSelected: "products selected",
    selectAll: "Select All",
    deselect: "Deselect",
    searchPlaceholder: "Search products to include...",
    previewCatalogueBtn: "Preview Catalogue",
    backToSettings: "Back to Settings",
    previewTitle: "Catalogue Preview",
    previewSubtitle: "Customer Brochure View",
    publicDocument: "Public Customer Document",
    publicDocNotice: "Internal financial figures strictly hidden",
    shareAsPdf: "Share as PDF",
    shareAsWhatsApp: "Share as Text / WhatsApp Message",
    editSelection: "Edit Selection",
    available: "Available",
    outOfStock: "Out of stock",
    onOrder: "On order",
    thanksMessage: "Thank you for your business!",
    validNotice: "Valid according to available stocks",
    itemsCount: "Items",
    noProductsFound: "No matching products",
    noProductsFoundDesc: "Try searching for other items or clear the filter",
  },

  // 11. receipts — receipt text
  receipts: {
    title: "Receipt",
    subtitle: "Receipt Text",
    storeName: "Store Name",
    storeAddress: "Store Address",
    date: "Date",
    time: "Time",
    saleItems: "Sale Items",
    subtotal: "Subtotal",
    tax: "Tax",
    totalAmount: "Total Amount",
    amountPaid: "Amount Paid",
    changeDue: "Change Due",
    customerName: "Customer Name",
    phoneNumber: "Phone Number",
    thankYou: "Thank you for visiting",
    comeAgain: "We hope to see you again"
  },

  // 12. exports — CSV export labels
  exports: {
    title: "Export",
    subtitle: "Export Data",
    exportCSV: "Export CSV",
    exportSelected: "Export Selected",
    exportAll: "Export All",
    columns: "Columns",
    dateRange: "Date Range",
    from: "From",
    to: "To",
    exportingData: "Exporting data",
    exportCompleted: "Export completed",
    exportFailed: "Export failed",
    selectingData: "Select data to export",
    noDataToExport: "No data to export"
  },

  // 13. settings — settings sections
  settings: {
    title: "Settings",
    subtitle: "Application Settings",
    general: "General",
    language: "Language",
    currency: "Currency",
    notifications: "Notifications",
    about: "About",
    version: "Version",
    rateApp: "Rate App",
    shareApp: "Share App",
    logoutAllSessions: "Logout All Sessions",
    resetApp: "Reset App",
    languageArabic: "Arabic",
    languageFrench: "French",
    languageEnglish: "English",
    default: "Default"
  },

  // 14. voice — voice command messages
  voice: {
    title: "Voice Commands",
    subtitle: "Learn Commands",
    listening: "Listening",
    listeningError: "Listening Error",
    commandNotRecognized: "Command Not Recognized",
    sayProductName: "Say Product Name",
    sayPrice: "Say Price",
    sayQuantity: "Say Quantity",
    startSale: "Start Sale",
    cancelSale: "Cancel Sale",
    takePhoto: "Take Photo"
  },

  // 15. errors — error messages
  errors: {
    title: "Error",
    genericError: "Generic Error",
    networkError: "Network Error",
    tryAgain: "Try Again",
    somethingWentWrong: "Something Went Wrong",
    invalidInput: "Invalid Input",
    requiredField: "Required Field",
    unableToLoad: "Unable to Load",
    unableToSave: "Unable to Save",
    operationCancelled: "Operation Cancelled"
  },

  // 16. confirmations — confirmation dialog messages
  confirmations: {
    title: "Confirmation",
    message: "Are you sure?",
    cancel: "Cancel",
    ok: "OK",
    deleteItem: "Delete this item?",
    deleteSale: "Delete this sale?",
    clearDatabase: "Clear Database?",
    thisActionCannotBeUndone: "This action cannot be undone",
    yesDelete: "Yes, Delete",
    noKeep: "No, Keep"
  },

  // 17. emptyStates — empty list messages
  emptyStates: {
    title: "No Items",
    subtitle: "List is Empty",
    description: "No items yet. Add the first item",
    addFirstItem: "Add First Item",
    noProducts: "No Products",
    noCustomers: "No Customers",
    noSales: "No Sales",
    noPayments: "No Payments",
    noInventory: "No Inventory"
  },

  // 18. permissions — permission request messages
  permissions: {
    title: "Permission Requests",
    camera: "Camera",
    microphone: "Microphone",
    storage: "Storage",
    location: "Location",
    cameraDescription: "This feature requires camera access",
    microphoneDescription: "This feature requires microphone access",
    storageDescription: "This feature requires storage access",
    locationDescription: "This feature requires location access",
    deny: "Deny",
    allow: "Allow"
  }
};