export default {
  // 1. common — general UI labels, buttons, actions
  common: {
    appText: "Texte de l'application",
    screen: "Écran",
    header: "En-tête",
    back: "Retour",
    action: "Action",
    primaryButton: "Bouton principal",
    secondaryButton: "Bouton secondaire",
    iconButton: "Icône",
    card: "Carreau",
    emptyState: "État vide",
    icon: "Icône",
    title: "Titre",
    subtitle: "Sous-titre",
    loading: "Chargement",
    error: "Erreur",
    retry: "Réessayer",
    notFound: "Page introuvable",
    notFoundBackToHome: "Retour à l'accueil",
    confirmDialog: "Confirmation",
    confirmTitle: "Confirmation",
    confirmMessage: "Êtes-vous sûr de vouloir continuer ?",
    confirmCancel: "Annuler",
    confirmOk: "OK",
    money: "DZD",
    positive: "Positif",
    negative: "Négatif",
    search: "Recherche",
    placeholder: "Rechercher...",
    formField: "Champ",
    label: "Libellé",
    errorMessage: "Erreur",
    statusPaid: "Payé",
    statusPartial: "Partiel",
    statusCancelled: "Annulé"
  },

  // 2. onboarding — onboarding flow strings
  onboarding: {
    appText: "Texte de l'application",
    screen: "Écran",
    header: "En-tête",
    back: "Retour",
    title: "Bienvenue sur Dukkan OS",
    subtitle: "Application pour micro-entrepreneurs algériens",
    description: "Enregistrez les ventes, suivez les clients, gérez les stocks",
    getStarted: "Commencer",
    skip: "Sauter"
  },

  // 3. navigation — tab labels, headers
  navigation: {
    home: "Accueil",
    products: "Produits",
    sales: "Ventes",
    customers: "Clients",
    catalogue: "Catalogue",
    more: "Plus",
    dashboard: "Tableau de bord",
    settings: "Paramètres",
    profile: "Profil",
    logout: "Déconnexion"
  },

  // 4. dashboard — dashboard cards, summaries
  dashboard: {
    title: "Tableau de bord",
    totalSales: "Ventes totales",
    totalCustomers: "Clients totaux",
    lowStockAlert: "Alerte de stock faible",
    estimatedProfit: "Profit estimé",
    todaySales: "Ventes d'aujourd'hui",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois",
    stockValue: "Valeur du stock",
    noSalesYet: "Pas de ventes encore",
    newSale: "Nouvelle vente"
  },

  // 5. products — product management
  products: {
    title: "Produits",
    subtitle: "Suivi des stocks et inventaire",
    addProduct: "Ajouter un produit",
    editProduct: "Modifier le produit",
    newItem: "Nouvel article",
    name: "Nom",
    description: "Description",
    price: "Prix",
    costPrice: "Prix d'achat",
    barcode: "Code-barres",
    sku: "SKU",
    category: "Catégorie",
    status: "Statut",
    active: "Actif",
    inactive: "Inactif",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    noProductsYet: "Aucun produit pour l'instant",
    totalItems: "Articles totaux",
    totalValue: "Valeur totale",
    lowStockCount: "Stock faible ({{count}})",
    searchPlaceholder: "Rechercher par nom ou SKU",
    filterAll: "Tous",
    filterLowStock: "Stock faible",
    filterOutOfStock: "Rupture",
    filterArchived: "Archivés",
    itemsCount: "{{count}} articles",
    lowStockBadge: "{{count}} Stock faible",
    inStock: "En stock",
    outOfStock: "Rupture de stock",
    lowStock: "Stock faible",
    lowStockMin: "Stock faible (min: {{min}})",
    stock: "Stock",
    onHand: "En stock",
    minThreshold: "Seuil minimal",
    stockStatus: "État du stock",
    needsRestock: "Réapprovisionner",
    normalStock: "Normal",
    salePrice: "Prix de vente",
    estimatedProfit: "Marge estimée",
    profitMargin: "Marge bénéficiaire",
    sellingPrice: "Prix de vente",
    costAndProfit: "Coût & Marge",
    adjustStock: "Ajuster le stock",
    inventoryHistory: "Historique du stock",
    recentMovements: "Mouvements récents de stock",
    noHistory: "Aucun historique de stock",
    lowStockAlert: "Alerte stock faible",
    lowStockAlertDesc: "Seulement {{stock}} restants. Le seuil minimal est de {{min}}.",
    generalInformation: "Informations générales",
    itemDetails: "Détails de l'article",
    pricingAndMargins: "Prix & Marges",
    stockInventory: "Gestion du stock",
    openingStock: "Stock initial",
    unit: "Unité",
    units: "unités",
    minAlertThreshold: "Seuil d'alerte minimal",
    safeFloor: "Seuil de sécurité",
    alertsWhenLow: "Alerte lorsque le stock atteint ce seuil",
    skuBarcodeOptional: "SKU / Code-barres (Optionnel)",
    categoryOptional: "Catégorie (Optionnelle)",
    newCategory: "Nouvelle catégorie",
    addCategoryPrompt: "Entrez le nom de la catégorie",
    scanBarcode: "Scanner le code-barres",
    valid: "Valide",
    productNameRequired: "Le nom du produit est requis",
    saveProduct: "Enregistrer le produit",
    productUpdated: "Produit mis à jour avec succès",
    productCreated: "Produit créé avec succès",
    adjustmentMethod: "Méthode d'ajustement",
    setNewTotal: "Définir nouveau total",
    addRemove: "Ajouter / Retirer (+/−)",
    newTotalQuantity: "Nouvelle quantité totale",
    adjustmentQuantity: "Quantité d'ajustement (+/−)",
    currentOnHand: "Stock actuel",
    adjustmentReason: "Motif d'ajustement",
    reasonRequired: "Requis",
    reasonDelivery: "Nouvelle livraison / Réapprovisionnement",
    reasonCorrection: "Correction d'inventaire",
    reasonDamaged: "Marchandise endommagée ou expirée",
    reasonReturn: "Retour client",
    reasonOther: "Autre",
    referenceNote: "Référence / Note",
    referenceNoteOptional: "Optionnel",
    referenceNotePlaceholder: "ex: Bon de livraison #BL-4890, grossiste",
    impactSummary: "Résumé d'impact",
    newInventoryBalance: "Nouveau solde de stock :",
    inventoryValueChange: "Variation de la valeur :",
    atCost: "au coût d'achat",
    confirmAdjustment: "Confirmer l'ajustement",
    adjustmentSuccess: "Stock ajusté avec succès",
    archiveProduct: "Archiver le produit",
    reactivateProduct: "Réactiver le produit",
    archiveConfirm: "Êtes-vous sûr de vouloir archiver ce produit ?",
    copiedToClipboard: "Copié dans le presse-papiers",
  },

  // 6. inventory — stock, movements
  inventory: {
    title: "Stock",
    subtitle: "Gestion du stock",
    totalItems: "Articles totaux",
    lowStock: "Stock faible",
    outOfStock: "Rupture de stock",
    restock: "Réapprovisionnement",
    addStock: "Ajouter du stock",
    removeStock: "Retirer du stock",
    movementTitle: "Mouvement de stock",
    movementIn: "Entrée",
    movementOut: "Sortie",
    date: "Date",
    quantity: "Quantité",
    product: "Produit",
    noStockYet: " aucune mouvement de stock pour l'instant"
  },

  // 7. sales — sale flow, cart, checkout
  sales: {
    title: "Ventes",
    subtitle: "Flux de ventes",
    newSale: "Nouvelle vente",
    cart: "Panier",
    checkout: "Caisses",
    paymentMethod: "Méthode de paiement",
    cash: "Espèces",
    electronic: "Électronique",
    mixed: "Mixte",
    partial: "Partiel",
    credit: "Crédit",
    amount: "Montant",
    quantity: "Quantité",
    total: "Total",
    change: "Reste",
    pay: "Payer",
    confirmSale: "Confirmer la vente",
    saleCancelled: "Vente annulée",
    saleCompleted: "Vente terminée",
    noSalesYet: "Pas de ventes pour l'instant"
  },

  // 8. customers — customer management
  customers: {
    title: "Clients",
    subtitle: "Gestion des clients",
    activeDebt: "Dette active",
    activityTimeline: "Historique d'activité",
    add: "Ajouter",
    addCustomer: "Ajouter un client",
    addPayment: "Ajouter un paiement",
    all: "Tous",
    amountPlaceholder: "0",
    archived: "Archivés",
    carnetDette: "Carnet Dette • Registre du magasin",
    cash: "Espèces",
    cashDescription: "Espèces directes au comptoir",
    cleared: "Soldé",
    clientSince: "Client depuis",
    closeWithoutSending: "Fermer sans envoyer",
    confirmPayment: "Confirmer le paiement",
    creditLimit: "Limite de crédit",
    creditLimitHelp: "Dette maximale avant alerte",
    creditSaleHistory: "Historique des ventes à crédit",
    creditSales: "Ventes à crédit",
    currentDebt: "Dette actuelle",
    customAmount: "Autre montant",
    debt: "Dette",
    debtToCollect: "Dette à recouvrer",
    edahabia: "Électronique",
    edahabiaDescription: "TPE Edahabia / CIB",
    editCustomer: "Modifier le client",
    electronic: "Électronique",
    email: "E-mail",
    fullDebt: "Dette totale",
    hasDebt: "Dette",
    identityAndContact: "Identité & Contact",
    immediateDue: "Dû immédiatement",
    impactOnBalance: "Impact sur le solde",
    invalidAmount: "Montant de paiement invalide",
    merchantNote: "Note marchand",
    messagePreview: "Aperçu instantané",
    name: "Nom",
    nameHelp: "Nom complet ou surnom familier",
    nameRequired: "Le nom du client est requis",
    newBalance: "Nouveau solde de dette",
    newCustomer: "Nouveau client",
    noCustomersYet: "Aucun client pour l'instant",
    noDebt: "Payé",
    noHistory: "Aucun historique pour l'instant",
    noNotes: "Aucune note ajoutée",
    notFound: "Client introuvable",
    noTimeline: "Aucune activité pour l'instant",
    note: "Note client",
    noteHelp: "Contexte utile visible en caisse et sur le carnet",
    notePlaceholder: "ex. Voisin du 2ème étage, client régulier",
    notes: "Notes",
    overdue: "En retard",
    overPaymentWarning: "Le montant dépasse la dette actuelle",
    overPaymentWarningDetails: "Dette restante: {{remaining}} DZD. Excédent: {{excess}} DZD.",
    overPaymentWarningTitle: "Avis de limite de paiement",
    paymentAmount: "Montant du paiement",
    paymentCleared: "{{amount}} DZD reçus de {{customer}}",
    paymentFailed: "Échec de l'enregistrement du paiement",
    paymentHistory: "Historique des paiements",
    paymentMethod: "Mode de paiement",
    paymentReminderPreview: "Aperçu du rappel de paiement",
    payments: "Paiements",
    paymentSuccess: "Paiement enregistré",
    paymentToApply: "Paiement à appliquer",
    phone: "Téléphone",
    phoneHelp: "Utilisé pour les rappels WhatsApp et reçus",
    phonePlaceholder: "0550 12 34 56",
    recordPayment: "Enregistrer un paiement",
    referenceNote: "Référence / Note",
    reminderSent: "Rappel partagé avec succès",
    saveCustomer: "Enregistrer le client",
    searchPlaceholder: "Rechercher par nom ou tél.",
    selectChannel: "Canal d'envoi principal",
    selectLanguage: "Langue du message",
    sendReminder: "Envoyer le rappel",
    sendViaSMS: "Envoyer par SMS",
    sendViaWhatsApp: "Envoyer via WhatsApp",
    settled: "Réglé",
    settlementDetails: "Détails du règlement",
    shareReminder: "Partager rappel (WhatsApp)",
    sms: "SMS Direct",
    totalCustomers: "Total clients",
    totalDebt: "Dette totale",
    viewDetails: "Voir les détails",
    whatsapp: "WhatsApp",
    withDebt: "Avec dette",
  },

  // 9. payments — payment recording
  payments: {
    title: "Moyens de paiement",
    subtitle: "Enregistrement des paiements",
    receivePayment: "Recevoir un paiement",
    paymentAmount: "Montant du paiement",
    paymentMethod: "Méthode de paiement",
    cashPayment: "Paiement espèces",
    electronicPayment: "Paiement électronique",
    reference: "Référence",
    date: "Date",
    amountReceived: "Montant reçu",
    remainingBalance: "Solde restant",
    paymentCompleted: "Paiement terminé",
    noPaymentsYet: "Aucun paiement pour l'instant"
  },

  // 10. catalogue — catalogue generation
  catalogue: {
    title: "Catalogue",
    subtitle: "Génération du catalogue",
    generateCatalogue: "Générer le catalogue",
    productsIncluded: "Produits inclus",
    excludeCustomerData: "Exclure les données clients",
    generate: "Générer",
    csvFormat: "Format CSV",
    exporting: "Exportation",
    catalogueExported: "Catalogue exporté",
    noProductsForCatalogue: "Pas de produits pour le catalogue",
    settingsTitle: "Paramètres du catalogue",
    settingsSubtitle: "Brochure client partageable",
    readyToShare: "Prêt à partager",
    instantShowcase: "Vitrine instantanée",
    instantShowcaseDesc: "Créez une brochure de produits élégante en un clic. Vos marges et onglets restent strictement confidentiels.",
    displayPreferences: "Préférences d'affichage",
    showRetailPrices: "Afficher les prix de vente",
    showRetailPricesDesc: "Affiche le prix de vente à côté de chaque article",
    hideOutOfStock: "Masquer les articles en rupture",
    hideOutOfStockDesc: "Filtre automatiquement les articles à quantité zéro",
    publicHeader: "En-tête public & Contact",
    shopHeaderTitle: "Titre du commerce",
    orderWhatsApp: "WhatsApp / Mobile de commande",
    storeLocation: "Adresse du commerce",
    welcomeNote: "Message d'accueil de la brochure",
    guaranteedPrivacy: "Confidentialité garantie",
    guaranteedPrivacyDesc: "Les valeurs d'achat internes, dettes, références fournisseurs et stocks d'entrepôt sont strictement exclus.",
    selectProductsBtn: "Choisir les produits",
    selectProductsTitle: "Sélectionner les produits",
    selectProductsSubtitle: "Choisissez les produits à inclure dans la brochure",
    productsSelected: "produits sélectionnés",
    selectAll: "Tout sélectionner",
    deselect: "Désélectionner",
    searchPlaceholder: "Rechercher des produits à inclure...",
    previewCatalogueBtn: "Aperçu du catalogue",
    backToSettings: "Retour aux paramètres",
    previewTitle: "Aperçu du catalogue",
    previewSubtitle: "Aperçu de la brochure client",
    publicDocument: "Document client public",
    publicDocNotice: "Chiffres financiers internes strictement masqués",
    shareAsPdf: "Partager en PDF",
    shareAsWhatsApp: "Partager texte / Message WhatsApp",
    editSelection: "Modifier la sélection",
    available: "Disponible",
    outOfStock: "Rupture de stock",
    onOrder: "Sur commande",
    thanksMessage: "Merci de votre fidélité !",
    validNotice: "Valable selon stocks disponibles",
    itemsCount: "Articles",
    noProductsFound: "Aucun produit correspondant",
    noProductsFoundDesc: "Essayez de rechercher d'autres articles ou effacez le filtre",
  },

  // 11. receipts — receipt text
  receipts: {
    title: "Recu",
    subtitle: "Texu du reçu",
    storeName: "Nom du magasin",
    storeAddress: "Adresse du magasin",
    date: "Date",
    time: "Heure",
    saleItems: "Articles de la vente",
    subtotal: "Sous-total",
    tax: "Taxe",
    totalAmount: "Montant total",
    amountPaid: "Montant payé",
    changeDue: "Reste",
    customerName: "Nom du client",
    phoneNumber: "Numéro de téléphone",
    thankYou: "Merci de votre visite",
    comeAgain: "Nous espérons vous revoir bientôt"
  },

  // 12. exports — CSV export labels
  exports: {
    title: "Exportation",
    subtitle: "Exportation de données",
    exportCSV: "Exporter CSV",
    exportSelected: "Exporter la sélection",
    exportAll: "Exporter tout",
    columns: "Colonnes",
    dateRange: "Plage de dates",
    from: "Depuis",
    to: "Jusqu'à",
    exportingData: "Exportation en cours",
    exportCompleted: "Exportation terminée",
    exportFailed: "Échec de l'exportation",
    selectingData: "Sélectionnez les données à exporter",
    noDataToExport: "Aucune donnée à exporter"
  },

  // 13. settings — settings sections
  settings: {
    title: "Paramètres",
    subtitle: "Paramètres de l'application",
    general: "Général",
    language: "Langue",
    currency: "Devise",
    notifications: "Notifications",
    about: "À propos",
    version: "Version",
    rateApp: "Évaluez l'application",
    shareApp: "Partagez l'application",
    logoutAllSessions: "Déconnexion de toutes les sessions",
    resetApp: "Réinitialiser l'application",
    languageArabic: "Arabe",
    languageFrench: "Français",
    languageEnglish: "Anglais",
    default: "Par défaut"
  },

  // 14. voice — voice command messages
  voice: {
    title: "Commandes vocales",
    subtitle: "Découvrez les commandes",
    listening: "En écoute",
    listeningError: "Erreur d'écoute",
    commandNotRecognized: "Commande non reconnue",
    sayProductName: "Dites le nom du produit",
    sayPrice: "Dites le prix",
    sayQuantity: "Dites la quantité",
    startSale: "Commencer la vente",
    cancelSale: "Annuler la vente",
    takePhoto: "Prendre une photo"
  },

  // 15. errors — error messages
  errors: {
    title: "Erreur",
    genericError: "Erreur générale",
    networkError: "Erreur de réseau",
    tryAgain: "Essayez encore",
    somethingWentWrong: "Quelque chose s'est mal passé",
    invalidInput: "Entrée invalide",
    requiredField: "Champ requis",
    unableToLoad: "Impossible de charger",
    unableToSave: "Impossible de sauvegarder",
    operationCancelled: "Opération annulée"
  },

  // 16. confirmations — confirmation dialog messages
  confirmations: {
    title: "Confirmation",
    message: "Êtes-vous sûr ?",
    cancel: "Annuler",
    ok: "OK",
    deleteItem: "Supprimer cet élément ?",
    deleteSale: "Supprimer cette vente ?",
    clearDatabase: "Effacer la base de données ?",
    thisActionCannotBeUndone: "Cet acte ne peut pas être annulé",
    yesDelete: "Oui, supprimer",
    noKeep: "Non, conserver"
  },

  // 17. emptyStates — empty list messages
  emptyStates: {
    title: "Aucun élément",
    subtitle: "La liste est vide",
    description: "Il n'y a pas d'éléments pour l'instant. Ajoutez le premier élément",
    addFirstItem: "Ajouter le premier élément",
    noProducts: "Pas de produits",
    noCustomers: "Pas de clients",
    noSales: "Pas de ventes",
    noPayments: "Pas de paiements",
    noInventory: "Pas de mouvement de stock"
  },

  // 18. permissions — permission request messages
  permissions: {
    title: "Demandes d'autorisations",
    camera: "Accès à la caméra",
    microphone: "Accès au microphone",
    storage: "Accès au stockage",
    location: "Accès à la localisation",
    cameraDescription: "Cette fonctionnalité nécessite l'accès à la caméra",
    microphoneDescription: "Cette fonctionnalité nécessite l'accès au microphone",
    storageDescription: "Cette fonctionnalité nécessite l'accès au stockage",
    locationDescription: "Cette fonctionnalité nécessite l'accès à la localisation",
    deny: "Refuser",
    allow: "Autoriser"
  }
};